<a href="https://colab.research.google.com/github/BIGBOSS-FOX/CS-513-Final-Project-Job-Termination-Classification/blob/master/ANN_Final_Project_Daoyuan_Chen_%26_Haopeng_Hu.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Load the "attrition_data.csv"



In [1]:
import pandas as pd

data = pd.read_csv("attrition_data.csv")

data

EMP_ID  ANNUAL_RATE  HRLY_RATE  ...  PREVYR_3 PREVYR_4 PREVYR_5
0     3285941608        33615         22  ...         0        0        0
1     3687079832        70675         40  ...         3        2        3
2     7209970080        34320         23  ...         3        2        3
3     9084013977       103199         59  ...         0        0        0
4     4566148978       141801         71  ...         2        2        2
...          ...          ...        ...  ...       ...      ...      ...
9607  8595959073        34636         23  ...         0        0        0
9608  4606362550        34962         27  ...         0        0        0
9609  5856364670        39286         27  ...         0        0        0
9610  5388746486        39145         27  ...         0        0        0
9611  6401616257        90726         50  ...         0        0        0

[9612 rows x 27 columns]

# Summary data

In [2]:
data.describe(include='all')

EMP_ID   ANNUAL_RATE  ...     PREVYR_4     PREVYR_5
count   9.612000e+03  9.612000e+03  ...  9612.000000  9612.000000
unique           NaN           NaN  ...          NaN          NaN
top              NaN           NaN  ...          NaN          NaN
freq             NaN           NaN  ...          NaN          NaN
mean    5.168687e+09  8.938563e+04  ...     0.617561     0.466188
std     2.394707e+09  5.843344e+04  ...     1.102402     0.971020
min     1.000475e+09  1.678600e+04  ...     0.000000     0.000000
25%     3.092187e+09  5.085550e+04  ...     0.000000     0.000000
50%     5.213208e+09  7.421050e+04  ...     0.000000     0.000000
75%     7.249635e+09  1.088115e+05  ...     1.000000     0.000000
max     9.996000e+09  1.250924e+06  ...     5.000000     5.000000

[11 rows x 27 columns]

In [3]:
data.dtypes

EMP_ID                      int64
ANNUAL_RATE                 int64
HRLY_RATE                   int64
JOBCODE                     int64
ETHNICITY                  object
SEX                        object
MARITAL_STATUS             object
JOB_SATISFACTION            int64
AGE                         int64
NUMBER_OF_TEAM_CHANGED     object
REFERRAL_SOURCE            object
HIRE_MONTH                 object
REHIRE                       bool
TERMINATION_YEAR          float64
IS_FIRST_JOB               object
TRAVELLED_REQUIRED         object
PERFORMANCE_RATING          int64
DISABLED_EMP               object
DISABLED_VET               object
EDUCATION_LEVEL            object
STATUS                     object
JOB_GROUP                  object
PREVYR_1                    int64
PREVYR_2                    int64
PREVYR_3                    int64
PREVYR_4                    int64
PREVYR_5                    int64
dtype: object

# Drop "EMP_ID" and "TERMINATION_YEAR"

In [6]:
data.drop(["EMP_ID", "TERMINATION_YEAR"], axis=1, inplace=True)

data

ANNUAL_RATE  HRLY_RATE  JOBCODE  ... PREVYR_3 PREVYR_4 PREVYR_5
0           33615         22    71850  ...        0        0        0
1           70675         40    59806  ...        3        2        3
2           34320         23    60311  ...        3        2        3
3          103199         59    16233  ...        0        0        0
4          141801         71    64415  ...        2        2        2
...           ...        ...      ...  ...      ...      ...      ...
9607        34636         23    58258  ...        0        0        0
9608        34962         27    58258  ...        0        0        0
9609        39286         27    36545  ...        0        0        0
9610        39145         27    44203  ...        0        0        0
9611        90726         50    89546  ...        0        0        0

[9612 rows x 25 columns]

# Replace all " " with a random ethnicity in "ETHNICITY"

In [7]:
pd.unique(data['ETHNICITY'])

array(['BLACK', 'ASIAN', 'WHITE', 'HISPA', 'PACIF', 'TWO', 'AMIND', ' '],
      dtype=object)

In [8]:
import random
random_ethnicity = random.choice(data[data['ETHNICITY'] != " "]['ETHNICITY'])
random_ethnicity

'ASIAN'

In [9]:
index_list = data.index[data['ETHNICITY'] == " "].tolist()
index_list

[2934]

In [0]:
data['ETHNICITY'].replace(" ", random_ethnicity, inplace = True)

In [11]:
data['ETHNICITY'][index_list[0]]

'ASIAN'

In [12]:
pd.unique(data['ETHNICITY'])

array(['BLACK', 'ASIAN', 'WHITE', 'HISPA', 'PACIF', 'TWO', 'AMIND'],
      dtype=object)

In [13]:
data['ETHNICITY'].describe(include='all')

count      9612
unique        7
top       WHITE
freq       5820
Name: ETHNICITY, dtype: object

# Replace all " " with "Unknown" in "REFERRAL_SOURCE"

In [14]:
pd.unique(data['REFERRAL_SOURCE'])

array(['Client Referral', 'Executive Referral', 'Former Employee/Intern',
       'Direct Sourcing', 'Inroads', 'Unknown', nan, 'Job Fair',
       'Print Advertisement', 'Corporate Career Site', 'Agency',
       'College Recommendation', 'Job Posting',
       'Job Boards/Online Advertising', 'Open House',
       'College Recruiting(UnderGrad)', 'E-Strat', 'Unsolicited',
       'Staffing Agency', 'Other Source'], dtype=object)

In [0]:
data['REFERRAL_SOURCE'].fillna('Unknown', inplace=True)

In [16]:
pd.unique(data['REFERRAL_SOURCE'])

array(['Client Referral', 'Executive Referral', 'Former Employee/Intern',
       'Direct Sourcing', 'Inroads', 'Unknown', 'Job Fair',
       'Print Advertisement', 'Corporate Career Site', 'Agency',
       'College Recommendation', 'Job Posting',
       'Job Boards/Online Advertising', 'Open House',
       'College Recruiting(UnderGrad)', 'E-Strat', 'Unsolicited',
       'Staffing Agency', 'Other Source'], dtype=object)

In [17]:
data['REFERRAL_SOURCE'].describe(include='all')

count        9612
unique         19
top       Unknown
freq          917
Name: REFERRAL_SOURCE, dtype: object

In [18]:
data['REFERRAL_SOURCE']

0              Client Referral
1           Executive Referral
2       Former Employee/Intern
3              Direct Sourcing
4                      Inroads
                 ...          
9607           Staffing Agency
9608                   Unknown
9609        Executive Referral
9610                Open House
9611               Job Posting
Name: REFERRAL_SOURCE, Length: 9612, dtype: object

# Retrieve numpy array

In [31]:
dataset = data.values

dataset.shape

(9612, 25)

# Perform min-max scaling each numerical feature column to the range [0,1]

In [30]:
from sklearn.preprocessing import MinMaxScaler

mms = MinMaxScaler()
num = ['ANNUAL_RATE', 'HRLY_RATE', 'JOB_SATISFACTION', 'AGE', 'PERFORMANCE_RATING', 'PREVYR_1', 'PREVYR_2', 'PREVYR_3', 'PREVYR_4', 'PREVYR_5']
dataset_num = data[num].values
mms.fit(dataset_num)
dataset_num_norm = mms.transform(dataset_num)
dataset_num_norm.shape

(9612, 10)

# Perform one-hot encoding on each categorical feature column

In [57]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder()
cat = ['JOBCODE', 'ETHNICITY', 'SEX', 'MARITAL_STATUS', 'NUMBER_OF_TEAM_CHANGED', 'REFERRAL_SOURCE', 'HIRE_MONTH', 'REHIRE', 'IS_FIRST_JOB', 'TRAVELLED_REQUIRED', 'DISABLED_EMP', 'DISABLED_VET', 'EDUCATION_LEVEL', 'JOB_GROUP']
dataset_cat = data[cat].values
# format all fields as string
dataset_cat = dataset_cat.astype(str)
ohe.fit(dataset_cat)
dataset_cat_enc = ohe.transform(dataset_cat).todense()
dataset_cat_enc

matrix([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]])

# Perform one-hot encoding on label column

In [32]:
from sklearn.preprocessing import LabelBinarizer

lb = LabelBinarizer()
dataset_label = data['STATUS'].values
lb.fit(dataset_label)
dataset_label_enc = lb.transform(dataset_label)
dataset_label_enc.shape


(9612, 1)

# Concatenate normalized numerical features and one-hot encoded categorical features into `X` and denote label by `y`

In [59]:
import numpy as np

X = np.hstack([dataset_num_norm, dataset_cat_enc])
y = dataset_label_enc
X.shape, y.shape

((9612, 1457), (9612, 1))

# Use 30% test 70% training data

In [62]:
from sklearn.model_selection import train_test_split

# split into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((6728, 1457), (2884, 1457), (6728, 1), (2884, 1))

## Use Keras to train a neural network with one 5-node hidden layer and a 1-node sigmoid output layer

In [64]:
from keras.models import Sequential
from keras.layers import Dense

# define the  model
model = Sequential()
model.add(Dense(5, input_dim=X_train.shape[1], activation='relu'))
model.add(Dense(1, activation='sigmoid'))
# print the summary of the model.
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 5)                 7290      
_________________________________________________________________
dense_4 (Dense)              (None, 1)                 6         
Total params: 7,296
Trainable params: 7,296
Non-trainable params: 0
_________________________________________________________________


In [0]:
# compile the keras model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [66]:
# fit the keras model on the dataset
model.fit(X_train, y_train, epochs=100, batch_size=16)

Epoch 1/100
6728/6728 [==============================] - 1s 124us/step - loss: 0.6389 - accuracy: 0.6403
Epoch 2/100
6728/6728 [==============================] - 1s 81us/step - loss: 0.5529 - accuracy: 0.7503
Epoch 3/100
6728/6728 [==============================] - 1s 80us/step - loss: 0.5039 - accuracy: 0.7721
Epoch 4/100
6728/6728 [==============================] - 1s 81us/step - loss: 0.4750 - accuracy: 0.7836
Epoch 5/100
6728/6728 [==============================] - 1s 81us/step - loss: 0.4550 - accuracy: 0.7870
Epoch 6/100
6728/6728 [==============================] - 1s 82us/step - loss: 0.4413 - accuracy: 0.7915
Epoch 7/100
6728/6728 [==============================] - 1s 82us/step - loss: 0.4304 - accuracy: 0.7955
Epoch 8/100
6728/6728 [==============================] - 1s 82us/step - loss: 0.4216 - accuracy: 0.7990
Epoch 9/100
6728/6728 [==============================] - 1s 83us/step - loss: 0.4155 - accuracy: 0.8038
Epoch 10/100
6728/6728 [==============================] - 1s 91

# Evaluate the accuracy of the prediction

In [70]:
# evaluate the keras model
_, accuracy = model.evaluate(X_test, y_test)
print('accuracy = ' + str(accuracy))

2884/2884 [==============================] - 0s 34us/step
accuracy = 0.7534673810005188


In [72]:
# prediction from the keras model
y_pred = model.predict_classes(X_test)
y_pred

array([[0],
       [0],
       [1],
       ...,
       [0],
       [1],
       [1]], dtype=int32)

In [74]:
# A table to compare y_pred with y_test
y_compare = np.hstack((y_test, y_pred))
y_compare

array([[0, 0],
       [0, 0],
       [0, 1],
       ...,
       [1, 0],
       [1, 1],
       [1, 1]])